name: Java CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Upload
        uses: actions/upload-artifact@v3.2.1-node20
        with:
            name: 'upload'
            path: './*'
            retention-days: 30
